name: Pull changes and deploy API
on: [push]
jobs:
  build:
    name: Pull changes and deploy API
    runs-on: self-hosted
    steps:
    - name: multiple command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al