name: Pull changes and deploy API
on: [push]
jobs:

  build:
    name: Build
    runs-on: self-hosted
    steps:
    - name: Executing remote command
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          whoami
          ls -al
